package io.xh.toolbox.datalab

import io.xh.hoist.security.AccessAll
import io.xh.toolbox.BaseController

/**
 * HTTP transport for the Data 2.0 measurement harness test-data API (HARN-02 HTTP path).
 *
 * Serves a seeded snapshot and successive deterministic diff batches generated by {@link DataLabService}.
 * Routes resolve via the standard Grails convention used throughout Toolbox (no app-level UrlMappings
 * file exists - controllers are mapped by `/$controller/$action`), so these actions are reachable at:
 *   GET /dataLab/snapshot
 *   GET /dataLab/diff
 *
 * Both the HTTP `diff` action here and the WebSocket DataLabPushService deliver the IDENTICAL batch
 * shape produced by DataLabService, so the client ingest adapter resolves either transport to the
 * same two-op contract (snapshot -> Cube.loadDataAsync, diff -> Cube.updateDataAsync). Access is
 * open, consistent with the other Toolbox example endpoints.
 */
@AccessAll
class DataLabController extends BaseController {

    DataLabService dataLabService

    /**
     * Return a seeded leaf-row snapshot whose shape is driven by request params.
     * Params: leafRowCount, fieldCount, fieldTypeMix (JSON map via fieldTypeMix.* or repeated),
     * dimensions, dimCardinality, seed. See DataLabService.generateSnapshot.
     */
    def snapshot() {
        renderJSON(dataLabService.generateSnapshot(parseShapeParams()))
    }

    /**
     * Return one deterministic update batch for the given iteration cursor. Successive polls with an
     * incrementing `iteration` return successive deterministic batches (the HTTP-poll equivalent of a
     * WebSocket stream).
     * Params: the shape params above PLUS pattern, breadth, batchSize, iteration.
     */
    def diff() {
        renderJSON(dataLabService.generateBatch(parseUpdateParams()))
    }

    //------------------------
    // Implementation
    //------------------------
    private Map parseShapeParams() {
        return [
            leafRowCount  : asInt(params.leafRowCount),
            fieldCount    : asInt(params.fieldCount),
            dimensions    : asInt(params.dimensions),
            dimCardinality: asInt(params.dimCardinality),
            fieldTypeMix  : parseFieldTypeMix(),
            seed          : asLong(params.seed)
        ].findAll { k, v -> v != null }
    }

    private Map parseUpdateParams() {
        return parseShapeParams() + [
            pattern  : params.pattern ?: null,
            breadth  : asInt(params.breadth),
            batchSize: asInt(params.batchSize),
            iteration: asInt(params.iteration)
        ].findAll { k, v -> v != null }
    }

    /**
     * Field-type mix may arrive as flattened params (fieldTypeMix.number=5, fieldTypeMix.string=3, ...).
     * Returns null if none supplied so the service applies its default mix.
     */
    private Map parseFieldTypeMix() {
        def mix = params.fieldTypeMix
        if (mix instanceof Map && mix) {
            return [
                number: asInt(mix.number),
                string: asInt(mix.string),
                date  : asInt(mix.date),
                object: asInt(mix.object)
            ].findAll { k, v -> v != null }
        }
        return null
    }

    private static Integer asInt(Object v) {
        if (v == null || v == '') return null
        try { return (v as BigDecimal).intValue() } catch (ignored) { return null }
    }

    private static Long asLong(Object v) {
        if (v == null || v == '') return null
        try { return (v as BigDecimal).longValue() } catch (ignored) { return null }
    }
}
