# Note Toolbox is deliberately using the next tag here, built off of xh/xh-nginx develop branch.
# Production apps are recommended to use latest, which is built off of master.
FROM xhio/xh-nginx:next
COPY app.conf $XH_NGINX_CONFIG_PATH/
COPY build/ $XH_NGINX_CONTENT_PATH/