package io.xh.toolbox.datalab

import io.xh.hoist.BaseService

import java.util.concurrent.ConcurrentHashMap

/**
 * WebSocket push transport for the Data 2.0 measurement harness test-data API (HARN-02 WS path).
 *
 * Streams seeded, deterministic update batches - generated by {@link DataLabService} - to harness
 * clients over Hoist Core's `webSocketService`, on a dedicated harness topic ({@link #TOPIC}) and a
 * distinct set of channels from the portfolio demo, so harness load never perturbs the existing
 * example (RESEARCH Open Question 4).
 *
 * This is the WS-push half of HARN-02; only the delivery mechanism differs from the HTTP diff in
 * {@link DataLabController}. Both carry the IDENTICAL batch shape produced by DataLabService, so the
 * client resolves either transport to the same two-op ingest contract (snapshot -> Cube.loadDataAsync,
 * diff -> Cube.updateDataAsync).
 *
 * Lifecycle: the client calls `start` (with its channelKey + scenario knobs) to begin a stream for a
 * measurement iteration, and `stop` to end it cleanly between iterations. A single base timer ticks
 * at {@link #TICK_MS}; each active {@link Stream} advances at its own configured `ratePerSec` and
 * stops itself once `durationSec` elapses. Inactive/closed channels are culled automatically.
 *
 * Honored update knobs (delegated to DataLabService.generateBatch) - orthogonal axes:
 *  - cadence    'steady' (constant batches) | 'burst' (spikes every 5th tick, lighter between).
 *  - updateMode 'incremental' (per-row diffs) | 'fullReplace' (re-snapshot signal, op:'replace',
 *               driving client Cube.loadDataAsync).
 *  - batchSize / breadth - magnitude knobs (rows per tick / fields per row), independent of the above.
 */
class DataLabPushService extends BaseService {

    /** Dedicated harness topic - distinct from the portfolio demo's channels/topics. */
    static final String TOPIC = 'xhDataLab/updates'

    /** Base timer cadence. Per-stream rate is derived against this tick. */
    static final long TICK_MS = 100

    def webSocketService,
        dataLabService

    private final Map<String, Stream> streams = new ConcurrentHashMap<>()

    void init() {
        // intervalUnits defaults to 1 (interval interpreted in milliseconds).
        createTimer(
            name: 'pushDataLabUpdates',
            runFn: this.&tickAllStreams,
            interval: TICK_MS,
            delay: true
        )
    }

    /**
     * Begin (or restart) an update stream for a client connection.
     *
     * @param channelKey - the client's unique WebSocket connection key.
     * @param scenarioParams - the shape + update knobs (leafRowCount, fieldCount, fieldTypeMix,
     *        dimensions, seed, pattern, breadth, batchSize) PLUS streaming knobs:
     *          - ratePerSec  (double) - batches pushed per second. Default 10.
     *          - durationSec (int)    - auto-stop after this many seconds; <=0 means run until stopped.
     */
    void start(String channelKey, Map scenarioParams) {
        if (!channelKey) return
        streams[channelKey] = new Stream(channelKey, scenarioParams ?: [:])
        logInfo("Started DataLab push stream", [
            channel: channelKey,
            cadence: scenarioParams?.cadence,
            updateMode: scenarioParams?.updateMode
        ])
    }

    /** Stop and remove the stream for the given channel. Safe to call when no stream exists. */
    void stop(String channelKey) {
        if (streams.remove(channelKey) != null) {
            logInfo("Stopped DataLab push stream", [channel: channelKey])
        }
    }

    /** Stop all active streams (e.g. on harness teardown). */
    void stopAll() {
        streams.clear()
    }

    Map getAdminStats() {[
        topic         : TOPIC,
        tickMs        : TICK_MS,
        activeStreams : streams.size()
    ]}

    //------------------------
    // Implementation
    //------------------------
    private void tickAllStreams() {
        if (streams.isEmpty()) return
        cullClosedChannels()

        long now = System.currentTimeMillis()
        streams.values().each { Stream stream ->
            // Auto-stop expired streams.
            if (stream.isExpired(now)) {
                stop(stream.channelKey)
                return
            }
            // Respect each stream's configured rate against the base tick.
            if (!stream.dueForPush(now)) return

            Map batch = dataLabService.generateBatch(stream.batchParams())
            webSocketService.pushToChannel(stream.channelKey, TOPIC, batch)
            stream.advance(now)
        }
    }

    private void cullClosedChannels() {
        streams.keySet().findAll { !webSocketService.hasChannel(it) }.each { stop(it) }
    }

    /** Per-connection stream state: scenario knobs, rate accounting, and iteration cursor. */
    private static class Stream {
        final String channelKey
        final Map scenarioParams
        final long ratePerSecMillisInterval
        final long startedAt
        final long durationMs

        private int iteration = 0
        private long lastPushAt = 0

        Stream(String channelKey, Map params) {
            this.channelKey = channelKey
            this.scenarioParams = params
            double rate = asDouble(params.ratePerSec, 10.0d)
            this.ratePerSecMillisInterval = rate > 0 ? Math.max(1L, (long) (1000.0d / rate)) : 1L
            int durationSec = asInt(params.durationSec, 0)
            this.startedAt = System.currentTimeMillis()
            this.durationMs = durationSec > 0 ? durationSec * 1000L : 0L
        }

        boolean isExpired(long now) {
            durationMs > 0 && (now - startedAt) >= durationMs
        }

        boolean dueForPush(long now) {
            (now - lastPushAt) >= ratePerSecMillisInterval
        }

        /** Params for DataLabService.generateBatch, carrying the current iteration cursor. */
        Map batchParams() {
            scenarioParams + [iteration: iteration]
        }

        void advance(long now) {
            iteration++
            lastPushAt = now
        }

        private static double asDouble(Object v, double dflt) {
            if (v == null || v == '') return dflt
            try { return (v as BigDecimal).doubleValue() } catch (ignored) { return dflt }
        }

        private static int asInt(Object v, int dflt) {
            if (v == null || v == '') return dflt
            try { return (v as BigDecimal).intValue() } catch (ignored) { return dflt }
        }
    }
}
