package io.xh.toolbox.admin

import io.xh.hoist.config.ConfigService
import io.xh.hoist.email.EmailService
import io.xh.hoist.security.AccessRequiresRole
import io.xh.toolbox.BaseController
import org.springframework.core.io.ByteArrayResource

/**
 * Exercises `EmailService` from Admin > Tests > Email.
 *
 * Forwards whatever args the page posts to `sendEmail` as a plain Map, so the runtime checks of the
 * named-parameter variant (unknown keys, missing `to`, type mismatches) run exactly as they would
 * for a dynamic caller. Attachments are generated here on request in each supported source type,
 * plus a deliberately invalid one.
 *
 * Unlike a normal controller, `send` catches Throwable so that an `AssertionError` from the arg
 * check is reported back to the page as a result rather than a 500.
 */
@AccessRequiresRole('HOIST_ADMIN')
class EmailTestController extends BaseController {

    static final List<String> CONFIG_NAMES = [
        'xhEmailDefaultSender', 'xhEmailDefaultDomain', 'xhEmailFilter', 'xhEmailOverride'
    ]

    ConfigService configService
    EmailService emailService

    /** Current values of the configs that govern EmailService, raw and as parsed by the service. */
    def configs() {
        renderJSON(CONFIG_NAMES.collectEntries {
            [it, [raw: configService.getString(it), parsed: emailService.parseMailConfig(it)]]
        })
    }

    /** Run `EmailService.parseAddresses` on an arbitrary string. */
    def parseAddresses(String value) {
        renderJSON([input: value, result: emailService.parseAddresses(value)])
    }

    /**
     * Send an email with the args posted as JSON. An `attachmentType` key, if present, is replaced
     * by a generated `attachments` entry of that source type - see {@link #createAttachment}.
     */
    def send() {
        Map args = new LinkedHashMap(parseRequestJSON())
        String attachmentType = args.remove('attachmentType')
        if (attachmentType) args.attachments = createAttachment(attachmentType)
        // Always rethrow so a send failure is reported to the page rather than only logged.
        args.throwError = true

        long start = System.currentTimeMillis()
        Map ret = [args: args.collectEntries { k, v -> [k, k == 'attachments' ? "<$attachmentType>" : v] }]
        try {
            emailService.sendEmail(args)
            ret.success = true
        } catch (Throwable t) {
            ret.success = false
            ret.error = t.class.name
            ret.message = t.message
        }
        ret.elapsedMs = System.currentTimeMillis() - start
        renderJSON(ret)
    }

    //------------------------
    // Implementation
    //------------------------
    private Map createAttachment(String type) {
        byte[] bytes = "Attachment generated by Toolbox EmailTestController at ${new Date()}\n".bytes
        Object source
        switch (type) {
            case 'bytes':
                source = bytes
                break
            case 'file':
                File file = File.createTempFile('email-test', '.txt')
                file.deleteOnExit()
                file.bytes = bytes
                source = file
                break
            case 'inputStreamSource':
                source = new ByteArrayResource(bytes)
                break
            case 'invalid':
                source = 'not a supported contentSource'
                break
            default:
                throw new IllegalArgumentException("Unknown attachmentType: $type")
        }
        return [fileName: 'email-test.txt', contentType: 'text/plain', contentSource: source]
    }
}
